AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  graalvm-kotlin-aws-lambda


Parameters:
  Profile:
    Type: String
    AllowedValues:
      - prod
      - staging
    Description: Enter profile name prod or staging.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  GraalvmKotlinApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Profile}
  GraalvmKotlinAwsLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: graalvm-kotlin-aws-lambda # Path to the root directory containing code and dependencies.
      Handler: kim.myeongjae.graalvmkotlin.awslambda.MyFunction::handleRequest
      FunctionName: !Sub "GraalvmKotlinAwsLambda-${Profile}"
      Runtime: provided.al2023
      Architectures:
      - arm64
      MemorySize: 128
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        GraalvmKotlinAwsLambda:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref GraalvmKotlinApiGateway
    Metadata:
      BuildMethod: makefile

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GraalvmKotlinApiGateway:
    Description: API Gateway endpoint URL for Hello World function
    Value: !Sub "https://${GraalvmKotlinApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Profile}/hello/"
  GraalvmKotlinAwsLambda:
    Description: GraalvmKotlinAwsLambda Lambda Function ARN
    Value: !GetAtt GraalvmKotlinAwsLambda.Arn
  GraalvmKotlinAwsLambdaIamRole:
    Description: Implicit IAM Role created for GraalvmKotlinAwsLambda function
    Value: !GetAtt GraalvmKotlinAwsLambdaRole.Arn
